#!/bin/bash
LISTDIR=blocklists

if [ ! -d $LISTDIR ]; then
  mkdir $LISTDIR
fi

cd $LISTDIR

echo "* Updating blocklists in $LISTDIR"

wget --no-check-certificate -N https://easylist-downloads.adblockplus.org/easylist.txt
wget --no-check-certificate -N https://easylist-downloads.adblockplus.org/easyprivacy.txt
wget --no-check-certificate -N https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
wget --no-check-certificate -N https://easylist-downloads.adblockplus.org/fanboy-social.txt
